Console.Write("Ввдеит a: ");
int a = Convert.ToInt32(Console.ReadLine());
int a2 = a * a;
Console.WriteLine($"a) за две операции {a2 * a2}");
int a4 = a2 * a2;
Console.WriteLine($"б) за три операции {a2 * a4}");
int a6 = a2 * a4;
Console.WriteLine($"в) за четыре операции {a6 * a}");
Console.WriteLine($"г) за три операции {a4 * a4}");
int a8 = a4 * a4;
Console.WriteLine($"д) за четыре операции {a8 * a}");
Console.WriteLine($"е) за четыре операции {a8 * a2}");
int a12 = a8 * a4;
Console.WriteLine($"ж) за пять операции {a12 * a}");
int a3 = a * a2;
int a7 = a3 * a4;
int a14 = a7 * a7;
Console.WriteLine($"з) за шесть операции {a14 * a}");
int a16 = a8 * a8;
int a20 = a16 * a4;
Console.WriteLine($"и) за шесть операции {a20 * a}");
int a24 = a16 * a8;
Console.WriteLine($"к) за шесть операции {a24 * a4}");
int a32 = a16 * a16;
Console.WriteLine($"л) за шесть операции {a32 * a32}");