Console.Write("Ввдеите число a: ");
int a = Convert.ToInt32(Console.ReadLine());
Console.Write("Ввдеите число b: ");
int b = Convert.ToInt32(Console.ReadLine());
Console.Write("Ввдеите число c: ");
int c = Convert.ToInt32(Console.ReadLine());
Console.WriteLine($"Тестовые значения: A = {a}, B = {b}, C = {c}\n");
bool conditionA = a > 100 && b > 100;
Console.WriteLine($"а) Каждое из чисел А и В больше 100:");
Console.WriteLine($"   Условие: A > 100 && B > 100");
Console.WriteLine($"   Результат: {conditionA}\n");
bool conditionB = (a % 2 == 0) ^ (b % 2 == 0);
Console.WriteLine($"б) Только одно из чисел А и В четное:");
Console.WriteLine($"   Условие: (A % 2 == 0) ^ (B % 2 == 0)");
Console.WriteLine($"   Результат: {conditionB}\n");
bool conditionC = a > 0 || b > 0;
Console.WriteLine($"в) Хотя бы одно из чисел А и В положительно:");
Console.WriteLine($"   Условие: A > 0 || B > 0");
Console.WriteLine($"   Результат: {conditionC}\n");
bool conditionD = a % 3 == 0 && b % 3 == 0 && c % 3 == 0;
Console.WriteLine($"г) Каждое из чисел А, В, С кратно трем:");
Console.WriteLine($"   Условие: A % 3 == 0 && B % 3 == 0 && C % 3 == 0");
Console.WriteLine($"   Результат: {conditionD}\n");
bool conditionE = (a < 50 ? 1 : 0) + (b < 50 ? 1 : 0) + (c < 50 ? 1 : 0) == 1;
Console.WriteLine($"д) Только одно из чисел А, В и С меньше 50:");
Console.WriteLine($"   Условие: (A < 50 ? 1 : 0) + (B < 50 ? 1 : 0) + (C < 50 ? 1 : 0) == 1");
Console.WriteLine($"   Результат: {conditionE}\n");
bool conditionF = a < 0 || b < 0 || c < 0;
Console.WriteLine($"е) Хотя бы одно из чисел А, В, С отрицательно:");
Console.WriteLine($"   Условие: A < 0 || B < 0 || C < 0");
Console.WriteLine($"   Результат: {conditionF}\n");